"""add weight to products

Revision ID: 2017fdc2b694
Revises: 3144ab40c8ef
Create Date: 2026-09-12 15:35:20.468405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2017fdc2b694'
down_revision: Union[str, Sequence[str], None] = '3144ab40c8ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('Weight', sa.DECIMAL(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'Weight')
    # ### end Alembic commands ###
